version: '2'
services:
  moodle:
    image: docker.io/bitnami/moodle:4
    ports:
      - '80:8080'
      - '3306:3306'
    environment:
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=10.0.0.7
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_NAME=moodle_db
      - MOODLE_DATABASE_PASSWORD=Huawei1#
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local